### ISSUE TITLE
Redirect Routes Don't Follow Caching Rules in Chrome 97

### ISSUE THREAD

**Issue by davidgolden** [GoogleChrome/workbox#3010]
**Library Affected**:
workbox-webpack-plugin (GenerateSW)

**Browser & Platform**:
Google Chrome 97

**Issue or Feature Request Description**:
If a redirect route is matched via `urlPattern` it is being served by the service worker regardless of the caching strategy. I believe it is a result of this addition in Chrome 97: https://chromestatus.com/feature/5752539724120064#details

**Comment by jeffposnick** [comment]
Thanks for reporting this—while I've seen the change to Chrome (and expect other browsers to follow with a similar change, if they haven't already, [as per this PR](https://github.com/whatwg/fetch/pull/1345)), I was not clear that there would be any Workbox-specific impact.

Would it be possible to share a link to a reproduction URL that demonstrates the specific behavior?

**Comment by jeffposnick** [comment]
I see that a bunch of folks have given this issue report a thumbs-up reaction—I just wanted to reiterate that I'm unclear right now specifically how users of Workbox are being impacted by this change, and if someone could pass along an example of unexpected breakage, we'll explore options to mitigate that.

**Comment by davidgolden** [comment]
I've spent some time trying to setup a minimum reproducible example and haven't succeeded yet. I plan to keep at it as I find time. If it helps, the condition that spurred this bug report in our production app is improper cache serving following an oauth login and redirect.

**Comment by jeffposnick** [comment]
Thanks!

If you have a production repro but would rather not share the URL publicly on GitHub, you can DM https://twitter.com/jeffposnick

Also, if you could just pass along what your current `registerRoute()` call looks like, that would help me understand what's going on without a full repro.

CC: @wanderview from Chrome's service worker team as an FYI.

**Comment by wanderview** [comment]
Likely due to this bug which is fixed in canary:

https://bugs.chromium.org/p/chromium/issues/detail?id=1286367

**Comment by davidgolden** [comment]
I just tested and it is not fixed for me in Version 99.0.4826.0 (Official Build) canary (arm64)

**Comment by wanderview** [comment]
The fix for that bug is in canary  99.0.4827.0.

**Comment by davidgolden** [comment]
@wanderview @jeffposnick I can confirm my issue has been resolved in the latest canary build. Thanks for your help!

**Comment by wanderview** [comment]
We are planning to get this into a stable release in the next week or so.
